#!/bin/bash

### BEGIN INIT INFO
# Provides: signaged
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start signaged at boot time
# Description: Start signaged at boot time
### END INIT INFO

signaged_home="/home/pi/signaged"
signaged_server="http://tv-indoor.192.168.25.11.xip.io"
machine_serial="CD9AK29HYCGPAH09"
pid_file="/var/run/signage.pid"

function running() {
    if [ -f "$pid_file" ]
    then
        pid=$(cat "$pid_file")
        output=$(ps aux | grep -v grep | grep "$pid")

        if [ "$output" != "" ]
        then
            return 0
        else
            return 1
        fi
    else
        return 1
    fi
}

function start() {
    if running
    then
        echo "signaged is already running"
    else
        echo "Starting signaged ..."
        $signaged_home/bin/signaged.rb $signaged_server $machine_serial & echo $! > "$pid_file"
    fi
}

function stop() {
    if running
    then
        echo "Stopping signaged ..."

        pid=$(cat "$pid_file")

        kill "$pid"

        if running
        then
            kill -9 "$pid"
        fi

        rm "$pid_file"
    else
        echo "signaged is not running"
    fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    status)
        if running
        then
            echo "signaged is started"
        else
            echo "signaged is stopped"
        fi
        ;;
    *)
        echo "Usage: $0 (start|stop|restart|status)"
        ;;
esac
