#!/bin/bash

### BEGIN INIT INFO
# Provides: signaged
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start signaged at boot time
# Description: Start signaged at boot time
### END INIT INFO

PATH=/usr/local/bin:$PATH

signaged_home="/home/pi/signaged"

pid_file="/var/run/signage.pid"

function running() {
    if [ -f "$pid_file" ]
    then
        return 0
    else
        return 1
    fi
}

function start() {
    if running
    then
        echo "signaged is already running"
    else
        sleep 15
        echo "Starting signaged ..."
        fbi -T 2 -reset
        fbi -T 2 -a -noverbose $signaged_home/assets/images/loading.png
        fbi -T 2 -reset
        cd $signaged_home && bin/signaged.rb & echo $! > "$pid_file"
    fi
}

function stop() {
    if running
    then
        echo "Stopping signaged ..."
        pid=$(cat "$pid_file")
        kill "$pid"
        rm "$pid_file"
    else
        echo "signaged is not running"
    fi
    killall fbi ruby omxplayer
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    status)
        if running
        then
            echo "signaged is started"
        else
            echo "signaged is stopped"
        fi
        ;;
    *)
        echo "Usage: $0 (start|stop|restart|status)"
        ;;
esac
